### ISSUE TITLE
Trained model doesn't load

### ISSUE THREAD

**Issue by aurel-au-velin-olymp** [teddykoker/pedalnet#4]
While the provided checkpoint `pedalnet.ckpt` works, loading a checkpoint that is trained with the exact code from the readme fails:

```
2020-09-15 12:56:43.145971: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    test(args)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 16, in test
    model = PedalNet.load_from_checkpoint(args.model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 153, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, strict=strict, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/saving.py", line 190, in _load_model_state
    model = cls(*cls_args, **cls_kwargs)
  File "/content/pedalnet/model.py", line 80, in __init__
    num_channels=hparams.num_channels,
AttributeError: 'dict' object has no attribute 'num_channels'
```

**Comment by teddykoker** [comment]
This might be because this code was using an older version of pytorch lightning.  Try `pip install pytorch_lightning==0.7.3`. I will update the code to work with the latest version soon, but this should fix it in the meantime. Please do let me know if you are still running into any issues.

**Comment by aurel-au-velin-olymp** [comment]
You are right. Thanks for pointing out and sorry - I should have used the actual `requirements.txt`!

**Comment by teddykoker** [comment]
Haha no worries! Glad it works :)
